### PR TITLE
Attempt at adding feedback for SETVAR.

### PR DESCRIPTION
**Pull request by ScrewLooseDan**
I've been using the SETVAR key for a handful of things, but with no feedback as to whether I pressed it or not felt a bit odd.  I quick tried this hack to blink on a keypress.  It appears to work.

Ideally, I'd be able to set values for key ON/OFF (like variable = 0, then key appear OFF).  But, for now I'm happy to get some feedback.

### CODE REVIEW

**Comment by kevinkahn** [comment]
I think the change you made will stop the variable from actually getting updated (though the key will blink) because you overrode the proc that responds to the keypress by doing the actual setting.  However, getting the blink feedback should be no problem - just need to add the blink call to the existing proc SetVar.  Actually you bumped into code I was modifying a while back and then got sidetracked because the blink option should already be there but isn't.  You might notice that there is a similar bit of unfinished code just above that SetVarKey stuff.  So since I really should fix all this and make things blink, can you say a bit more about what you'd actually like pressing the key to do?  Right now pressing it would set the variable to the VALUE set in the config file and (once fixed) blink to let you know it happened.  Sounds like you would like some different behavior?

**Comment by ScrewLooseDan** [comment]
<doh>  Of course, I didn't actually verify if it worked!  I was just excited to make the button blink!

And yes, looking at it now, I made it way more difficult that I needed to make it.  This is what I have now:

```
        def SetVar(self, presstype):
                isy.SetVar(self.VarID, self.Value)
                self.BlinkKey(self.Blink)
```
Verified that made the button blink AND the variable was actually updated!  LOL

I use a bunch of variables to enable/disable conditions in my programs (or change the timing the program runs).  Many of the variables are essentially binary, ie. 0=OFF, 1=ON.  It would be great to have way to not only set the variables, but also to see the current state.  

I recognize that this sort of feature might not have a very wide audience, so I'm happy with just getting feedback on the key press.

**Comment by kevinkahn** [comment]
Merged you change into the master so it will be in the next release.  Let me think a bit about how to do the kind of feedback you are interested in in some reasonably general way.

By the way, something that I just added that probably no one but me wants (but might at least interest you) is some limited support for subscribing to a MQTT broker.  My use for it is that I built a simple temperature/humidity sensor with WiFi that publishes its readings via MQTT.  I run a broker (mosquitto) and it lets me add the (*really*) local temperature to my weather screen.   I will probably try to generalize the idea a bit before I tell anyone about it since for the moment it is only hooked to the weather screens.  Just a random cute thing.

**Comment by ScrewLooseDan** [comment]
Thanks for the merge.  

I don't currently have any use for the MQTT subscriber, but I can certainly imagine it being useful and interesting.  I'll keep it in mind for future projects.

**Pull request merged**
